/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servicemonitors;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.Scanner;
import java.util.Vector;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Azuveike
 * The  class for the main GUI.
 */
public class ServiceParent extends javax.swing.JFrame {

    /**
     * Creates new form ServiceParent
     */
    Vector<Monitor_Gui> servicetable; // manually add entries unfortunately.
    Vector<javax.swing.JButton> buttoncontainer; // holds button locations. Needs to be synchronized
    ParentWorker p1;
    ParentWorker p2;
    ParentWorker p3;
    ParentWorker p4;
    ParentWorker p5;
    ParentWorker p6;
    ParentWorker p7;
    ParentWorker p8;
    ParentWorker p9;
    ParentWorker p10;
    ParentWorker p11;
    ParentWorker p12;
    ParentWorker p13;
    ParentWorker p14;
    ParentWorker p15;
    Vector<ParentWorker> pcontainer;
    
    
    
    public ServiceParent() {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
        servicetable = new Vector<Monitor_Gui>(); // initialize our vector
        buttoncontainer = new Vector<javax.swing.JButton>();
        pcontainer = new Vector<ParentWorker>();
        pcontainer.add(p1);
        pcontainer.add(p2);
        pcontainer.add(p3);
        pcontainer.add(p4);
        pcontainer.add(p5);
        pcontainer.add(p6);
        pcontainer.add(p7);
        pcontainer.add(p8);
        pcontainer.add(p9);
        pcontainer.add(p10);
        pcontainer.add(p11);
        pcontainer.add(p12);
        pcontainer.add(p13);
        pcontainer.add(p14);
        pcontainer.add(p15);
         buttoncontainer.add(jButton1);
        buttoncontainer.add(jButton2);
        buttoncontainer.add(jButton3);
        buttoncontainer.add(jButton4);
        buttoncontainer.add(jButton5);
        buttoncontainer.add(jButton6);
        buttoncontainer.add(jButton7);
        buttoncontainer.add(jButton8);
        buttoncontainer.add(jButton9);
        buttoncontainer.add(jButton10);
        buttoncontainer.add(jButton11);
        buttoncontainer.add(jButton12);
        buttoncontainer.add(jButton13);
        buttoncontainer.add(jButton14);
        buttoncontainer.add(jButton15);
        p1 = null;
        for(javax.swing.JButton item: buttoncontainer)
      {
          item.setText(" Empty");
      }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel5.setText("jLabel1");

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton1");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton1");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel6.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel7.setText("jLabel1");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel8.setText("jLabel1");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel9.setText("jLabel1");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel10.setText("jLabel1");

        jButton11.setText("jButton1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("jButton1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton1");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("jButton1");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel11.setText("jLabel1");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel12.setText("jLabel1");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel13.setText("jLabel1");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel14.setText("jLabel1");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Offline.JPG"))); // NOI18N
        jLabel15.setText("jLabel1");

        jButton16.setText("Sync");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Sync");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Sync");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Sync");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Sync");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Sync");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("Sync");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Sync");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Sync");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("Sync");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("Sync");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Sync");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Sync");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("Sync");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("Sync");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("Save As");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("Load Config");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton32)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton21)
                            .addComponent(jButton22)
                            .addComponent(jButton23)
                            .addComponent(jButton24)
                            .addComponent(jButton25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton26)
                            .addComponent(jButton27)
                            .addComponent(jButton28)
                            .addComponent(jButton29)
                            .addComponent(jButton30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton31)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton26))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton27)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton28))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton29))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jButton30))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton22))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton31)
                    .addComponent(jButton32))
                .addGap(74, 74, 74))
        );

        jButton31.getAccessibleContext().setAccessibleName("jButton31");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(1) != null)
            {
                servicetable.elementAt(1).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
           //  jButton2.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(1).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(2) != null)
            {
                servicetable.elementAt(2).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
           // jButton3.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(2).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(3) != null)
            {
                servicetable.elementAt(3).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
           // jButton4.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(3).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         try{
            if(servicetable.elementAt(4) != null)
            {
                servicetable.elementAt(4).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton5.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(4).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        if(servicetable.isEmpty())
        {
            Monitor_Gui addme = new Monitor_Gui();
            //addme.pack();
           //  jButton1.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //servicetable.elementAt(0).pack();
                 servicetable.elementAt(0).setVisible(true);
                
                
            }
        });
        }
        else
        {
            servicetable.elementAt(0).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(5) != null)
            {
                servicetable.elementAt(5).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
         //   jButton6.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(5).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
         try{
            if(servicetable.elementAt(6) != null)
            {
                servicetable.elementAt(6).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
        //    jButton7.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(6).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(7) != null)
            {
                servicetable.elementAt(7).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton8.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(7).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(8) != null)
            {
                servicetable.elementAt(8).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton9.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(8).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         try{
            if(servicetable.elementAt(9) != null)
            {
                servicetable.elementAt(9).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton10.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(9).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(10) != null)
            {
                servicetable.elementAt(10).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton11.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(10).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(11) != null)
            {
                servicetable.elementAt(11).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
          //  jButton12.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(11).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(12) != null)
            {
                servicetable.elementAt(12).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
         //   jButton13.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(12).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(13) != null)
            {
                servicetable.elementAt(13).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
         //   jButton14.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(13).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try{
            if(servicetable.elementAt(14) != null)
            {
                servicetable.elementAt(14).setVisible(true);
            }
        } catch(ArrayIndexOutOfBoundsException s){
            
            Monitor_Gui addme = new Monitor_Gui();
         //   jButton15.setText(addme.par_name);
            servicetable.add(addme);
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 servicetable.elementAt(14).setVisible(true);
        }
        });
                }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        // Resync here
        if(p1 ==null)
        {
        p1 =  new ParentWorker(servicetable.elementAt(0).pworkers, servicetable.elementAt(0).sworkers,
                servicetable.elementAt(0).zworkers, jLabel1);
        jButton1.setText(servicetable.elementAt(0).par_name);
        p1.execute();
        }
        else
        {
            p1.cancel(true);
            p1 = null;
            p1 =  new ParentWorker(servicetable.elementAt(0).pworkers, servicetable.elementAt(0).sworkers,
               servicetable.elementAt(0).zworkers, jLabel1);
            jButton1.setText(servicetable.elementAt(0).par_name);
            p1.execute();
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         if(p2 ==null)
        {
        p2 =  new ParentWorker(servicetable.elementAt(1).pworkers, servicetable.elementAt(1).sworkers,
                servicetable.elementAt(1).zworkers, jLabel2);
        jButton2.setText(servicetable.elementAt(1).par_name);
        p2.execute();
        }
        else
        {
            p2.cancel(true);
            p2 = null;
            p2 =  new ParentWorker(servicetable.elementAt(1).pworkers, servicetable.elementAt(1).sworkers,
               servicetable.elementAt(1).zworkers, jLabel2);
            jButton2.setText(servicetable.elementAt(1).par_name);
            p2.execute();
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
          if(p3 ==null)
        {
        p3 =  new ParentWorker(servicetable.elementAt(2).pworkers, servicetable.elementAt(2).sworkers,
                servicetable.elementAt(2).zworkers, jLabel3);
        jButton3.setText(servicetable.elementAt(2).par_name);
        p3.execute();
        }
        else
        {
            p3.cancel(true);
            p3 = null;
            p3 =  new ParentWorker(servicetable.elementAt(2).pworkers, servicetable.elementAt(2).sworkers,
               servicetable.elementAt(2).zworkers, jLabel3);
            jButton3.setText(servicetable.elementAt(2).par_name);
            p3.execute();
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
          if(p4 ==null)
        {
        p4 =  new ParentWorker(servicetable.elementAt(3).pworkers, servicetable.elementAt(3).sworkers,
                servicetable.elementAt(3).zworkers, jLabel4);
        jButton4.setText(servicetable.elementAt(3).par_name);
        p4.execute();
        }
        else
        {
            p4.cancel(true);
            p4 = null;
            p4 =  new ParentWorker(servicetable.elementAt(3).pworkers, servicetable.elementAt(3).sworkers,
               servicetable.elementAt(3).zworkers, jLabel4);
            jButton4.setText(servicetable.elementAt(3).par_name);
            p4.execute();
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
          if(p5 ==null)
        {
        p5 =  new ParentWorker(servicetable.elementAt(4).pworkers, servicetable.elementAt(4).sworkers,
                servicetable.elementAt(4).zworkers, jLabel5);
        jButton5.setText(servicetable.elementAt(4).par_name);
        p5.execute();
        }
        else
        {
            p5.cancel(true);
            p5 = null;
            p5 =  new ParentWorker(servicetable.elementAt(4).pworkers, servicetable.elementAt(4).sworkers,
               servicetable.elementAt(4).zworkers, jLabel5);
            jButton5.setText(servicetable.elementAt(4).par_name);
            p5.execute();
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
         if(p6 ==null)
        {
        p6 =  new ParentWorker(servicetable.elementAt(5).pworkers, servicetable.elementAt(5).sworkers,
                servicetable.elementAt(5).zworkers, jLabel6);
        jButton6.setText(servicetable.elementAt(5).par_name);
        p6.execute();
        }
        else
        {
            p6.cancel(true);
            p6 = null;
            p6 =  new ParentWorker(servicetable.elementAt(5).pworkers, servicetable.elementAt(5).sworkers,
               servicetable.elementAt(5).zworkers, jLabel6);
            jButton6.setText(servicetable.elementAt(5).par_name);
            p6.execute();
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        if(p7 ==null)
        {
        p7 =  new ParentWorker(servicetable.elementAt(6).pworkers, servicetable.elementAt(6).sworkers,
                servicetable.elementAt(6).zworkers, jLabel7);
        jButton7.setText(servicetable.elementAt(6).par_name);
        p7.execute();
        }
        else
        {
            p7.cancel(true);
            p7 = null;
            p7 =  new ParentWorker(servicetable.elementAt(6).pworkers, servicetable.elementAt(6).sworkers,
               servicetable.elementAt(6).zworkers, jLabel7);
            jButton7.setText(servicetable.elementAt(6).par_name);
            p7.execute();
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
         if(p8 ==null)
        {
        p8 =  new ParentWorker(servicetable.elementAt(7).pworkers, servicetable.elementAt(7).sworkers,
                servicetable.elementAt(7).zworkers, jLabel8);
        jButton8.setText(servicetable.elementAt(7).par_name);
        p8.execute();
        }
        else
        {
            p8.cancel(true);
            p8 = null;
            p8 =  new ParentWorker(servicetable.elementAt(7).pworkers, servicetable.elementAt(7).sworkers,
               servicetable.elementAt(7).zworkers, jLabel8);
            jButton8.setText(servicetable.elementAt(7).par_name);
            p8.execute();
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        if(p9 ==null)
        {
        p9 =  new ParentWorker(servicetable.elementAt(8).pworkers, servicetable.elementAt(8).sworkers,
                servicetable.elementAt(8).zworkers, jLabel9);
        jButton9.setText(servicetable.elementAt(8).par_name);
        p9.execute();
        }
        else
        {
            p9.cancel(true);
            p9 = null;
            p9 =  new ParentWorker(servicetable.elementAt(8).pworkers, servicetable.elementAt(8).sworkers,
               servicetable.elementAt(8).zworkers, jLabel9);
            jButton9.setText(servicetable.elementAt(8).par_name);
            p9.execute();
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        if(p10 ==null)
        {
        p10 =  new ParentWorker(servicetable.elementAt(9).pworkers, servicetable.elementAt(9).sworkers,
                servicetable.elementAt(9).zworkers, jLabel10);
        jButton10.setText(servicetable.elementAt(9).par_name);
        p10.execute();
        }
        else
        {
            p10.cancel(true);
            p10 = null;
            p10 =  new ParentWorker(servicetable.elementAt(9).pworkers, servicetable.elementAt(9).sworkers,
               servicetable.elementAt(9).zworkers, jLabel10);
            jButton10.setText(servicetable.elementAt(9).par_name);
            p10.execute();
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        if(p11 ==null)
        {
        p11 =  new ParentWorker(servicetable.elementAt(10).pworkers, servicetable.elementAt(10).sworkers,
                servicetable.elementAt(10).zworkers, jLabel11);
        jButton11.setText(servicetable.elementAt(10).par_name);
        p11.execute();
        }
        else
        {
            p11.cancel(true);
            p11 = null;
            p11 =  new ParentWorker(servicetable.elementAt(10).pworkers, servicetable.elementAt(10).sworkers,
               servicetable.elementAt(10).zworkers, jLabel11);
            jButton11.setText(servicetable.elementAt(10).par_name);
            p11.execute();
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
         if(p12 ==null)
        {
        p12 =  new ParentWorker(servicetable.elementAt(11).pworkers, servicetable.elementAt(11).sworkers,
                servicetable.elementAt(11).zworkers, jLabel12);
        jButton12.setText(servicetable.elementAt(11).par_name);
        p12.execute();
        }
        else
        {
            p12.cancel(true);
            p12 = null;
            p12 =  new ParentWorker(servicetable.elementAt(11).pworkers, servicetable.elementAt(11).sworkers,
               servicetable.elementAt(11).zworkers, jLabel12);
            jButton12.setText(servicetable.elementAt(11).par_name);
            p12.execute();
        }
        
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        if(p13 ==null)
        {
        p13 =  new ParentWorker(servicetable.elementAt(12).pworkers, servicetable.elementAt(12).sworkers,
                servicetable.elementAt(12).zworkers, jLabel13);
        jButton13.setText(servicetable.elementAt(12).par_name);
        p13.execute();
        }
        else
        {
            p13.cancel(true);
            p13 = null;
            p13 =  new ParentWorker(servicetable.elementAt(12).pworkers, servicetable.elementAt(12).sworkers,
               servicetable.elementAt(12).zworkers, jLabel13);
            jButton13.setText(servicetable.elementAt(12).par_name);
            p13.execute();
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
          if(p14 ==null)
        {
        p14 =  new ParentWorker(servicetable.elementAt(13).pworkers, servicetable.elementAt(13).sworkers,
                servicetable.elementAt(13).zworkers, jLabel14);
        jButton14.setText(servicetable.elementAt(13).par_name);
        p14.execute();
        }
        else
        {
            p14.cancel(true);
            p14 = null;
            p14 =  new ParentWorker(servicetable.elementAt(13).pworkers, servicetable.elementAt(13).sworkers,
               servicetable.elementAt(13).zworkers, jLabel14);
            jButton14.setText(servicetable.elementAt(13).par_name);
            p14.execute();
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        if(p15 ==null)
        {
        p15 =  new ParentWorker(servicetable.elementAt(14).pworkers, servicetable.elementAt(14).sworkers,
                servicetable.elementAt(14).zworkers, jLabel15);
        jButton15.setText(servicetable.elementAt(14).par_name);
        p15.execute();
        }
        else
        {
            p15.cancel(true);
            p15 = null;
            p15 =  new ParentWorker(servicetable.elementAt(14).pworkers, servicetable.elementAt(14).sworkers,
               servicetable.elementAt(14).zworkers, jLabel15);
            jButton15.setText(servicetable.elementAt(14).par_name);
            p15.execute();
        }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        try {
            // TODO add your handling code here:
            load();
        } catch (IOException ex) {
            Logger.getLogger(ServiceParent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    public void save()
    {
        try {
           
             final JFileChooser fc = new JFileChooser();
            fc.showSaveDialog(this);
             Scanner reader = new Scanner(fc.getSelectedFile().toString());
            String filename = "";
             FileWriter file = new FileWriter(reader.next());
            
            for(Monitor_Gui item: servicetable)
            {
                file.write("Name:: " + "," + item.par_name + "," + item.service_count + System.lineSeparator());
                   for (Iterator it = item.pingmap.entrySet().iterator(); it.hasNext();) {
           
            Map.Entry<PingStatus,Integer> item2 = (Map.Entry<PingStatus,Integer>) it.next();
           // buttoncontainer.elementAt(item2.getValue().intValue()).setText("Ping: " + item2.getKey().hostname);
           // System.out.println("Ping: " + item.getKey().hostname);
            file.write( "Ping: " + "," + item2.getKey().hostname + "," + "Maintenance: " + "," +  item2.getKey().maintenance + "," + item2.getValue() + "," + item2.getKey().name + System.lineSeparator());
            
        }
                 for (Iterator it = item.servmap.entrySet().iterator(); it.hasNext();) {
           
            Map.Entry<ServiceStatus,Integer> item2 = (Map.Entry<ServiceStatus,Integer>) it.next();
           // buttoncontainer.elementAt(item2.getValue().intValue()).setText("Ping: " + item2.getKey().hostname);
           // System.out.println("Ping: " + item.getKey().hostname);
            file.write("Service: " + "," + item2.getKey().hostname + ","  + item2.getKey().portnum + "," + item2.getKey().maintenance + "," + item2.getValue()  + "," + item2.getKey().name + System.lineSeparator());
            
        }  
                 for (Iterator it = item.sitemap.entrySet().iterator(); it.hasNext();) {
           
            Map.Entry<siteSearcher,Integer> item2 = (Map.Entry<siteSearcher,Integer>) it.next();
           // buttoncontainer.elementAt(item2.getValue().intValue()).setText("Ping: " + item2.getKey().hostname);
           // System.out.println("Ping: " + item.getKey().hostname);
            file.write("Search: " + "," +  item2.getKey().url + ","   + item2.getKey().find + "," + item2.getKey().maintenance + "," + item2.getValue() + "," + item2.getKey().name + System.lineSeparator());
            
        }
            
                 
            }
            file.close();
        } catch (IOException ex) {
            Logger.getLogger(ServiceParent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public void load() throws FileNotFoundException, IOException
    {
        
        int counter = -1; // initialize to one so our container starts at 0.
         final JFileChooser fc = new JFileChooser();
            fc.showOpenDialog(this);

            
        BufferedReader br;// = new BufferedReader(new FileReader(reader.));
    try {
         Scanner reader = new Scanner(fc.getSelectedFile().getAbsolutePath());
                  br = new BufferedReader(new FileReader(reader.next()));
        String line = "";
        String splits[];
         line = br.readLine();
         Monitor_Gui addme = new Monitor_Gui();
        while (line != null) {
          //System.out.println(line);
           
            if(line.contains("Name::"))
            {
                addme = new Monitor_Gui();
                counter++;
                splits = line.split(",");
                
                addme.par_name = splits[1];
                addme.service_count = Integer.parseInt(splits[2]);
                line = br.readLine(); // go to next line
                if(line == null)
                    break;
                
            }
            while(  !line.contains("Name::" ))
            {
                        
                    //System.out.println("adding");
                    if(line.contains("Ping:"))
                    {
                    //  System.out.println("add a ping");
                         splits = line.split(",");
                         String host = (splits[1]);
                        boolean on = Boolean.parseBoolean(splits[3]);
                        int location = Integer.parseInt(splits[4]);
                        String n = splits[5];
                        PingStatus toadd = new PingStatus(host, on, n);
                        addme.pingmap.put(toadd, location);
                        addme.pingcontainer.add(toadd);
                        addme.dropdownmap.put(toadd, "\n Name: " + toadd.name + " Ping: " + host + "\n");
                        // addme.jComboBox1.addItem("\n Ping: " + host + "\n");
                        line = br.readLine(); // go to next line
                        if(line == null)
                        break;
                    }
                    else if(line.contains("Service:"))
                    {
                      //  System.out.println("add a service");
                        splits = line.split(",");
                        String host = (splits[1]);
                        int portnum = Integer.parseInt(splits[2]);
                        boolean on = Boolean.parseBoolean(splits[3]);
                        int location = Integer.parseInt(splits[4]);
                        String n = splits[5];
                        ServiceStatus toadd = new ServiceStatus(host, portnum, on, n);
                        addme.servmap.put(toadd, location);
                        addme.servcontainer.add(toadd);
                        addme.dropdownmap.put(toadd, "\n Name: " + toadd.name + " Service Check: " + host + " at port: " + portnum + "\n");
                        line = br.readLine(); // go to next line
                        if(line == null)
                        break;
                    }
                    else if(line.contains("Search: "))
                    {
                      //  System.out.println("add a site");
                        splits = line.split(",");
                        String host = (splits[1]);
                        String text  = splits[2];
                        boolean on = Boolean.parseBoolean(splits[3]);
                        int location = Integer.parseInt(splits[4]);
                        String n = splits[5];
                        siteSearcher toadd = new siteSearcher(host, text, on, n);
                        addme.sitemap.put(toadd, location);
                        addme.sitecontainer.add(toadd);
                        addme.dropdownmap.put(toadd," \n Name: " + toadd.name + " TextSearch: " + host + " for: " + text + "\n");
                        line = br.readLine(); // go to next line
                        if(line == null)
                        break;
                    }
                    
            }
             for (Iterator it = addme.pingmap.entrySet().iterator(); it.hasNext();) {
           
            Map.Entry<PingStatus,Integer> item = (Map.Entry<PingStatus,Integer>) it.next();
           // addme.buttoncontainer.elementAt(item.getValue().intValue()).setText("Ping: " + item.getKey().hostname);
            addme.buttoncontainer.elementAt(item.getValue().intValue()).setText( item.getKey().name);
           
        }
        
        for (Iterator it = addme.sitemap.entrySet().iterator(); it.hasNext();) {
            Map.Entry<siteSearcher,Integer> item = (Map.Entry<siteSearcher,Integer>) it.next();
            //addme.buttoncontainer.elementAt(item.getValue().intValue()).setText("SiteSearch: " + item.getKey().url);
             addme.buttoncontainer.elementAt(item.getValue().intValue()).setText( item.getKey().name);

        }
        
        for (Iterator it = addme.servmap.entrySet().iterator(); it.hasNext();) {
            Map.Entry<ServiceStatus,Integer> item = (Map.Entry<ServiceStatus,Integer>) it.next();
           // addme.buttoncontainer.elementAt(item.getValue().intValue()).setText("Servicecheck: " + item.getKey().hostname);
            addme.buttoncontainer.elementAt(item.getValue().intValue()).setText( item.getKey().name);

        }
            addme.loadMap();// loads drop down
            addme.pingers = new ArrayList<Future<Integer>>(); //   ArrayList<Future<Integer>>
            addme.searchers = new ArrayList<Future<Integer>>();
            addme.servers = new ArrayList<Future<Integer>>();
            addme.searchresults = new Vector<Integer>();
            addme.servresults = new Vector<Integer>();
            addme.pingresults = new Vector<Integer>(); //  Vector<Integer>
            addme.pworkers = new PingWorkers(addme.labelcontainer,addme.buttoncontainer,addme.pingcontainer,addme.pingers,addme.pingresults,addme.pingmap);
             
             addme.pworkers.execute();
             addme.sworkers = new ServiceWorkers(addme.labelcontainer,addme.buttoncontainer,addme.servcontainer,addme.servers,addme.servresults,addme.servmap);
           
            addme.sworkers.execute();
            addme.zworkers = new SiteWorker(addme.labelcontainer,addme.buttoncontainer,addme.sitecontainer,addme.searchers,addme.searchresults,addme.sitemap);
           
             addme.zworkers.execute();
            addme.first_run = true;
             // System.out.println("heeere?");
        
            servicetable.add(addme);
            
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //    servicetable.elementAt(counter).setVisible(false);
        }
        });
        
          //  p1 =  new ParentWorker(servicetable.elementAt(0).pworkers, servicetable.elementAt(0).sworkers,
          //      servicetable.elementAt(0).zworkers, jLabel1);
      //  jButton1.setText(servicetable.elementAt(0).par_name);
      //  p1.execute();
            //line = br.readLine();
        }// wend
        
        
      br.close();
    } finally {
        //br.close();
       // System.out.println(servicetable.toString());
    }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceParent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceParent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

 
    
}
